-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKCCBRcf2dbfZEs9k
WSghwOsekNXYHsiZsh4hl4/8JgegCgYIKoZIzj0DAQehRANCAARTH47A+LjJMwi/
Rk8Sk8LhHP6rA/KBhBzJM0lkgaSypETXrrS5UqCVKmmfeTniaU66MLcQzdBeNbhl
UNHlVtxO
-----END PRIVATE KEY-----